name: CI - Test Workflow
on: pull_request

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set GO111MODULE
        run: |
          go env -w GO111MODULE=on

      - name: Run Unit Tests
        uses: robherley/go-test-action@v0.1.0
        with:
          testArguments: ./...
